### ISSUE TITLE
zapsmall use

### ISSUE THREAD

**Issue by gherardovarando** [irenecrsn/gmat#18]
when using the `zapsmall` function we should set a different `digits` argument, the default is `digits = 7 `

**Comment by irenecrsn** [comment]
I have still some conflicts over using `zapsmall` inside the function... 

I mean, maybe we should just "hard-code" the zeros if `zapzeros = TRUE`, and change the tests to use `zapzeros = FALSE'` and then `zapsmall` (but inside the test) to ensure that the orthogonalization is working and we are "allowed" to hardcode the zeros (since it is a numeric error), just as we do in `diagdom`. Or we could just return the matrix with those numeric errors, add it as a note in the documentation, and let the user choose whether or not to use `zapsmall`.

What do you think?

**Comment by gherardovarando** [comment]
Yes I think we should hard code the zeros using the real adj matrix of the graph.
